<script>

// Definiing the promise
let myPromise = new Promise( 
     ( mySuccessFunction, myErrorfunction) => 
     {
        // The job done by the promise
        let jobSuccess=false;
        let sum=0;
        for(let i=0;i<5;i++){ sum=sum+i};

        jobSuccess=true;
        if(jobSuccess){
            mySuccessFunction(sum);
        }else{
            myErrorfunction(new Error("Could not do the sum"));
        }

     }
);

let f1 = (result) => console.log("result computed by the pronmise is ="+result);
let f2 = (error) => console.log("pronmise failed with error message  ="+error);

// Launch the promise 
myPromise
.then( res => f1(res) )
.catch( error => f2(error));


console.log("STATEMENT1");
console.log("STATEMENT2")
console.log("STATEMENT3")


</script>